namespace Latest_Staff_Portal.ViewModel
{
    public class PurchaseInvoice
    {
        public string PRN_No;
        public string DocumentType { get; set; }
        public string No { get; set; }
        public string BuyFromVendorNo { get; set; }
        public string BuyFromVendorName { get; set; }
        public string DirectorateCode1 { get; set; }
        public string DepartmentCode { get; set; }
        public string PostingDescription { get; set; }
        public string BuyFromAddress { get; set; }
        public string BuyFromAddress2 { get; set; }
        public string BuyFromCity { get; set; }
        public string BuyFromCounty { get; set; }
        public string BuyFromPostCode { get; set; }
        public string BuyFromCountryRegionCode { get; set; }
        public string BuyFromContactNo { get; set; }
        public string BuyFromContactPhoneNo { get; set; }
        public string BuyFromContactMobilePhoneNo { get; set; }
        public string BuyFromContactEmail { get; set; }
        public string BuyFromContact { get; set; }
        public string DocumentDate { get; set; }
        public string Posted { get; set; }
        public string ExpenseRequisitionNumber { get; set; }
        public string PostingDate { get; set; }
        public string VATReportingDate { get; set; }
        public string DueDate { get; set; }
        public int IncomingDocumentEntryNo { get; set; }
        public string VendorInvoiceNo { get; set; }
        public string PurchaserCode { get; set; }
        public string VendorOrderNo { get; set; }
        public string CampaignNo { get; set; }
        public string OrderAddressCode { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string AssignedUserID { get; set; }
        public string Status { get; set; }
        public string JobQueueStatus { get; set; }
        public string CurrencyCode { get; set; }
        public string ExpectedReceiptDate { get; set; }
        public bool PricesIncludingVAT { get; set; }
        public string VATBusPostingGroup { get; set; }
        public string VendorPostingGroup { get; set; }
        public string PaymentTermsCode { get; set; }
        public string PaymentMethodCode { get; set; }
        public string ReasonCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public int PaymentDiscountPercent { get; set; }
        public string PmtDiscountDate { get; set; }
        public string JournalTemplName { get; set; }
        public bool TaxLiable { get; set; }
        public string TaxAreaCode { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string PaymentReference { get; set; }
        public string CreditorNo { get; set; }
        public string OnHold { get; set; }
        public string ShippingOptionWithLocation { get; set; }
        public string LocationCode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToPostCode { get; set; }
        public string ShipToCountryRegionCode { get; set; }
        public string ShipToContact { get; set; }
        public string PayToOptions { get; set; }
        public string PayToName { get; set; }
        public string PayToAddress { get; set; }
        public string PayToAddress2 { get; set; }
        public string PayToCity { get; set; }
        public string PayToCounty { get; set; }
        public string PayToPostCode { get; set; }
        public string PayToCountryRegionCode { get; set; }
        public string PayToContactNo { get; set; }
        public string PayToContactPhoneNo { get; set; }
        public string PayToContactMobilePhoneNo { get; set; }
        public string PayToContactEmail { get; set; }
        public string PayToContact { get; set; }
        public string RemitToCode { get; set; }
        public string RemitToName { get; set; }
        public string RemitToAddress { get; set; }
        public string RemitToAddress2 { get; set; }
        public string RemitToCity { get; set; }
        public string RemitToCounty { get; set; }
        public string RemitToPostCode { get; set; }
        public string RemitToCountryRegionCode { get; set; }
        public string RemitToContact { get; set; }
        public string TransactionSpecification { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string EntryPoint { get; set; }
        public string Area { get; set; }
        public bool ApplicableForServDecl { get; set; }
        public string Amount { get; set; }
        public string DimensionSetId { get; set; }
        public string OrderNo { get; set; }
        public string Closed { get; set; }
        public string Cancelled { get; set; }
        public string Corrective { get; set; }
        public string Remaining_Amount { get; set; }
    }
    public class PurchaseInvoiceLines
    {
        public string DocumentType { get; set; }
        public string DocumentNo { get; set; }
        public int LineNo { get; set; }
        public string Type { get; set; }
        public string FilteredTypeField { get; set; }
        public string No { get; set; }
        public string ItemReferenceNo { get; set; }
        public string ICPartnerCode { get; set; }
        public string ICPartnerRefType { get; set; }
        public string ICPartnerReference { get; set; }
        public string VariantCode { get; set; }
        public bool Nonstock { get; set; }
        public string GenProdPostingGroup { get; set; }
        public string VATProdPostingGroup { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string ReturnReasonCode { get; set; }
        public string LocationCode { get; set; }
        public string BinCode { get; set; }
        public int Quantity { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string UnitOfMeasure { get; set; }
        public int DirectUnitCost { get; set; }
        public int IndirectCostPercent { get; set; }
        public int UnitCostLCY { get; set; }
        public int UnitPriceLCY { get; set; }
        public bool TaxLiable { get; set; }
        public string TaxAreaCode { get; set; }
        public string TaxGroupCode { get; set; }
        public bool UseTax { get; set; }
        public int LineDiscountPercent { get; set; }
        public int LineAmount { get; set; }
        public string AmountIncludingVAT { get; set; }
        public int LineDiscountAmount { get; set; }
        public bool AllowInvoiceDisc { get; set; }
        public int InvDiscountAmount { get; set; }
        public bool AllowItemChargeAssignment { get; set; }
        public int QtyToAssign { get; set; }
        public string ServiceTransactionTypeCode { get; set; }
        public bool ApplicableForServDecl { get; set; }
        public int QtyAssigned { get; set; }
        public string JobNo { get; set; }
        public string JobTaskNo { get; set; }
        public int JobPlanningLineNo { get; set; }
        public string JobLineType { get; set; }
        public int JobUnitPrice { get; set; }
        public int JobLineAmount { get; set; }
        public int JobLineDiscountAmount { get; set; }
        public int JobLineDiscountPercent { get; set; }
        public int JobTotalPrice { get; set; }
        public int JobUnitPriceLCY { get; set; }
        public int JobTotalPriceLCY { get; set; }
        public int JobLineAmountLCY { get; set; }
        public int JobLineDiscAmountLCY { get; set; }
        public string ProdOrderNo { get; set; }
        public string BlanketOrderNo { get; set; }
        public int BlanketOrderLineNo { get; set; }
        public string InsuranceNo { get; set; }
        public string FAPostingDate { get; set; }
        public string BudgetedFANo { get; set; }
        public string FAPostingType { get; set; }
        public string DepreciationBookCode { get; set; }
        public bool DeprUntilFAPostingDate { get; set; }
        public bool DeprAcquisitionCost { get; set; }
        public string DuplicateInDepreciationBook { get; set; }
        public bool UseDuplicationList { get; set; }
        public int ApplToItemEntry { get; set; }
        public string DeferralCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string ShortcutDimCode3 { get; set; }
        public string ShortcutDimCode4 { get; set; }
        public string ShortcutDimCode5 { get; set; }
        public string ShortcutDimCode6 { get; set; }
        public string ShortcutDimCode7 { get; set; }
        public string ShortcutDimCode8 { get; set; }
        public int GrossWeight { get; set; }
        public int NetWeight { get; set; }
        public int UnitVolume { get; set; }
        public int UnitsPerParcel { get; set; }
        public int AmountBeforeDiscount { get; set; }
        public int InvoiceDiscountAmount { get; set; }
        public int InvoiceDiscPct { get; set; }
        public int TotalAmountExclVAT { get; set; }
        public int TotalVATAmount { get; set; }
        public int TotalAmountInclVAT { get; set; }
    }


}